name: radiatroll
description: "Esta s贸lo es una app para hacer bromas, no es una radiaci贸n real, s贸lo es la reproducci贸n del sonido emitido por un medidor geiger."

publish_to: 'none' 

version: 2.0.1+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  sensors_plus: ^5.0.0       
  proximity_sensor: ^1.0.4   
  cupertino_icons: ^1.0.8
  volume_controller: ^2.0.7
  vibration: ^3.1.3 
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/geiger.mp3
    - assets/images/logo.png
    - assets/images/radiacion_activa.png
    - assets/images/sin_radiacion.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"